export default {
  login: "dxu5",
  id: 42157345,
  node_id: "MDQ6VXNlcjQyMTU3MzQ1",
  avatar_url: "https://avatars1.githubusercontent.com/u/42157345?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/dxu5",
  html_url: "https://github.com/dxu5",
  followers_url: "https://api.github.com/users/dxu5/followers",
  following_url: "https://api.github.com/users/dxu5/following{/other_user}",
  gists_url: "https://api.github.com/users/dxu5/gists{/gist_id}",
  starred_url: "https://api.github.com/users/dxu5/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/dxu5/subscriptions",
  organizations_url: "https://api.github.com/users/dxu5/orgs",
  repos_url: "https://api.github.com/users/dxu5/repos",
  events_url: "https://api.github.com/users/dxu5/events{/privacy}",
  received_events_url: "https://api.github.com/users/dxu5/received_events",
  type: "User",
  site_admin: false,
  name: "Derek Xu",
  company: "Brown University",
  blog: "https://dxu5.github.io/",
  location: "Los Angeles",
  email: null,
  hireable: null,
  bio: "Brown University Class of 2020",
  twitter_username: null,
  public_repos: 20,
  public_gists: 0,
  followers: 0,
  following: 0,
  created_at: "2018-08-06T22:38:28Z",
  updated_at: "2020-07-19T01:19:55Z",
};
